### ISSUE TITLE
ToDo - International Card Symbols

### ISSUE THREAD

**Issue by Sequenzer** [Sequenzer/BeatUp#2]
Missing Icons:

- [x] GER-drink: "Beer"
- [x] GER-food: "Wiener"
- [x] RUS-drink: "Vodka"
- [x] RUS-food: "Pelmeni"
- [x] CUB-drink: "Cuba Libre"
- [x] CUB-food: "cigar"
- [x] GHA-drink: "palm wine"
- [x] GHA-food: "Banku"
- [x] ESP-drink: "Paella"
- [x] ESP-food: "Sangria"
- [ ] ITA-drink: "missing"
- [ ] ITA-food: "pizza"
- [ ] GBR-drink: "tea"
- [ ] GBR-food: "fish and chips"
- [ ] FRA-drink: "Redwine"
- [ ] FRA-food: "frogs /snails"
- [ ] TUR-drink: "coffee"
- [ ] TUR-food: "Döner"
- [ ] JPN-drink: "Sake"
- [ ] JPN-food: "Sushi"
- [ ] MEX-drink: "Margarita"
- [ ] MEX-food: "Tacos"
- [ ] CAN-drink: "beerbottle"
- [ ] CAN-food: "Pancakes with maplesirup"
